{{- $templateName := "k8spsphostnamespace" }}
{{- $templateConfig := index .Values.constraintTemplates $templateName }}

{{- if $templateConfig.enabled }}
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: {{ $templateName }}
  labels:
    {{- include "gatekeeper.commonLabels" . | nindent 4 }}
  annotations:
    metadata.gatekeeper.sh/title: "Host Namespace"
    metadata.gatekeeper.sh/version: "1.1.0"
    description: |-
      Disallows sharing of host PID and IPC namespaces by pod containers.
      Corresponds to the `hostPID` and `hostIPC` fields in a PodSecurityPolicy.
      For more information, see https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces
spec:
  crd:
    spec:
      names:
        kind: K8sPSPHostNamespace
      validation:
        legacySchema: false
        openAPIV3Schema: # This template takes no parameters, so no 'properties' field.
          description: |-
            Disallows sharing of host PID and IPC namespaces by pod containers.
            Corresponds to the `hostPID` and `hostIPC` fields in a PodSecurityPolicy.
            For more information, see https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces
          type: object # The schema for the 'parameters' object, which is empty for this template.
  targets:
    - target: admission.k8s.gatekeeper.sh
      code:
        - engine: K8sNativeValidation
          source:
            validations:
              - expression: (has(request.operation) && request.operation == "UPDATE") || !variables.sharingNamespace
                messageExpression: '"Sharing the host namespace (hostPID or hostIPC) is not allowed for pod: " + object.metadata.name'
            variables:
              - name: sharingHostIPC
                expression: |
                  has(object.spec.hostIPC) ? object.spec.hostIPC : false
              - name: sharingHostPID
                expression: |
                  has(object.spec.hostPID) ? object.spec.hostPID : false
              - name: sharingNamespace
                expression: |
                  variables.sharingHostIPC || variables.sharingHostPID
        - engine: Rego
          source:
            libs:
              - |
                package lib.exclude_update

                is_update(review) {
                  review.operation == "UPDATE"
                }
            rego: |
              package k8spsphostnamespace

              import data.lib.exclude_update.is_update

              violation[{"msg": msg, "details": {}}] {
                # This policy applies to Pods, disallowing hostPID=true or hostIPC=true on CREATE.
                # Updates to existing pods are allowed by the is_update check.
                not is_update(input.review)
                input.review.object.kind == "Pod" # Ensure we are dealing with a Pod
                input_share_hostnamespace(input.review.object)
                msg := sprintf("Sharing the host namespace (hostPID or hostIPC) is not allowed for pod: %v", [input.review.object.metadata.name])
              }

              input_share_hostnamespace(o) {
                has(o.spec) # Ensure spec exists
                o.spec.hostPID == true
              }

              input_share_hostnamespace(o) {
                has(o.spec) # Ensure spec exists
                o.spec.hostIPC == true
              }
{{- end }}
