apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ratify
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.cloudthat.com/krishnapal.d/ratify.git  # Replace with your Git repo URL
    targetRevision: HEAD
    path: ratify
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ratify
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
