{{- if .Values.dockerConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-dockerconfig
data:
  .dockerconfigjson: {{ .Values.dockerConfig | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{ end }}