{{- if and .Values.cosign.enabled .Values.cosign.key}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-cosign-certificate
data:
  cosign.pub: {{ .Values.cosign.key | b64enc | quote }}
{{- end }}

---
{{- if and (eq (include "ratify.tlsCertsProvided" .) "false") (not (lookup "v1" "Secret" .Release.Namespace (include "ratify.tlsSecretName" .))) (not .Values.featureFlags.RATIFY_CERT_ROTATION) }}
{{- fail "You must provide a TLS certificate for Ratify to use or enable RATIFY_CERT_ROTATION to make Ratify generate its certificates."}}
{{- else if or (eq (include "ratify.tlsCertsProvided" .) "true") (and (eq (include "ratify.tlsCertsProvided" .) "false") (not (lookup "v1" "Secret" .Release.Namespace (include "ratify.tlsSecretName" .))) (.Values.featureFlags.RATIFY_CERT_ROTATION))}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-tls
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
data:
  {{ include "ratify.tlsSecret" . | nindent 2 }}
{{- end }}