apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratify.fullname" . }}
  labels:
    {{- include "ratify.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6001
      targetPort: 6001
  selector:
    {{- include "ratify.selectorLabels" . | nindent 4 }}
