apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ratify.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDGzCCAgOgAwIBAgIUTsx85qH1YvEGamjl/KYcr324TWgwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAwwScmF0aWZ5LnJhdGlmeTIuc3ZjMB4XDTI1MDYwOTA5MjEz
    NloXDTM1MDYwNzA5MjEzNlowHTEbMBkGA1UEAwwScmF0aWZ5LnJhdGlmeTIuc3Zj
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp7euTBHg3+WaUTXX5fAm
    RluSCOSrqE2jRhMKdbJgAzDKZWBhnoU+4eOAR7mj+IoFBRleeGQ7mOibWhHqpbOX
    i4Wf37dt0dfZytn6kky/mgl1RV5lO9iiqqgI3Dm/CN3nn860Y1hknIWnM/3KsTMy
    JwzGl8UZZ9wAO7xYQ6wxciICj/AinwZ1podb8GGxmwLZySlFZwA9j0J3nogAD4yG
    oegST2s98ksPO7t3jWwZBERgq5GSoPwv+L61Y0ofXfczeUWAvOCgdbrTyRtnT+Wk
    /TaWUAEYH5/r5InBiv0wHMqSDFlq04RtOy2wegPt3t1+K+sRqr2BXBeRNLNSZL7i
    PwIDAQABo1MwUTAdBgNVHQ4EFgQUhf6BkB+xmN0K/wsI8a67DwpTE/YwHwYDVR0j
    BBgwFoAUhf6BkB+xmN0K/wsI8a67DwpTE/YwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAULFHlX2SuKx+gBHk+suxxli82KYh/QSYMCcUrM5+EWLk
    6iSpemiJ/M+alxhHSJbwbKnigazQ3Ened3qOSSW5XAyFj+LJ1ol/MrYvmeYKhV81
    /aLYLSguFcG86Q4QVLQhPC4npojWkDPslMZzpAE3u0NIaLclW3A4QK1kDuH2pi75
    EkdqnoxWl+dxwfEEyJe+FK9z9AmEfXP6BGSQkOcr/C8d2zReRRJSYs5pZxtfRiwd
    kpfkAYBKOtaGs21+JJpusVv5UOAGlik1txpDqnoZWuk0x9GxSz4+ATfMl3+WeHJJ
    3CoDToIiGPTKybxLKsPLh5wiTNaBhcniGpENwq+pTA==
    -----END CERTIFICATE-----
  tls.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCnt65MEeDf5ZpR
    Ndfl8CZGW5II5KuoTaNGEwp1smADMMplYGGehT7h44BHuaP4igUFGV54ZDuY6Jta
    Eeqls5eLhZ/ft23R19nK2fqSTL+aCXVFXmU72KKqqAjcOb8I3eefzrRjWGSchacz
    /cqxMzInDMaXxRln3AA7vFhDrDFyIgKP8CKfBnWmh1vwYbGbAtnJKUVnAD2PQnee
    iAAPjIah6BJPaz3ySw87u3eNbBkERGCrkZKg/C/4vrVjSh9d9zN5RYC84KB1utPJ
    G2dP5aT9NpZQARgfn+vkicGK/TAcypIMWWrThG07LbB6A+3e3X4r6xGqvYFcF5E0
    s1JkvuI/AgMBAAECggEAE02x0vGP11U+4K/4zG9KiHiLo1hmZXWiIDOa1ZcVM+jO
    ssJYGf2uEiO0JQ050SZZk4+q7uJidaP4FXLQdgfonldf4kjja+6TE6TpESOiPeFu
    zPAjaLLzbf7vHiHLWgLoYN1Sp8iJs/YyG2rPhHum/xWaWeeGmAybPkTcR9Wuzzrp
    KBGNC7KTuM//wHdSDn9sBuQHraDZ8SVq2UtJMJXGrft7vx2Pjvtu1HuqsZ0PJig1
    4/u0GaJdrbNJUD5i9f5/roxbcLzCnFocRXkrvGV/PEH7k8ntSKP4eJuRGnkLymi/
    X64nV1ZaWwLMYPCUqdowxmeCW1oUzVuVPKD80yhoAQKBgQDUZsUx2KzlFpc9G7b0
    ZKoBYsyHbIISGP1qL44AeEUdSGPWi8dP2NK9Ntus5RXM7CLYiudVa4kzgMj4GYlV
    Kf5V7b0uNuq7FcwYCS+hTiKsP+jx447gUsMIMc92CI8YSfFVkS8HN093pw4FNv9D
    AFbMeB1lFUSD9wbfDqpfVoCUAQKBgQDKJN4QvJabNK+mzrmniBbZvy2U9UhBdFKy
    LpcVnx61wQYxsrHJxEAFukKMIgQSW2tYz3adjKfrh+mOD7GuH2xwF0p8gJdmERF/
    3KbwRnrL4Xl/KqffZ4wLJjhRwLyM7klpRAf5d5A7JATPalrIlbuD93e3JL9FkU7r
    XLPiLuJ2PwKBgQC6/Gp3knfLChNEwcRT7NbZd3/1bKopgoR92bWaZkb6G4OBGfby
    LUCBQO0tjVOe3vdiSQ6U3aGgjKzf9aM4LUrxnOTh7YjCANN3CYc760yM9Yp+gEWE
    6Hc4HJm2IJzQ1i+2k6SiJqg3/wJRxvP7qS3AvbGrDokN4AfVkNSeL8nsAQKBgE2D
    w6/xUWNk2bKCdUjb878+A1GqmTGYVJnFKeR9pv4VbbWjC3AOlGpd2WT5KkyLx+c/
    bwHNTRsRfCsgs4bMv/1fwQ1rFiNqiiZYy585t5708G0mQ0d04ovn9RLMcMEuIvJ9
    xv0PrzwufLW41+UxHb3mKH8PVVVs+jFg1A344phrAoGBALeOe0uL4QaDTb2fAEOO
    Zwi2SNv/djM2K83XJwFl4pxQWP7m7gWjFTUZNakblHgbT0y9SZhCxov+TdSOQl+k
    U7dZKa+LxXzoka5B76VRgm2LPzHusTOLx2TonGasLitPvNphcx6MXXkqNp8kvJDN
    9NQhbf/Yrv4/vhT8wnv+dg/z
    -----END PRIVATE KEY-----
